robot:
  robot_specifications:
    - footprint:
        footprint_specifications:
          radius: 0.1
          points:
            []
    - initial_pose:
        x: 0
        y: 0
        theta: 0
    - laser:
        laser_specifications:
          max_angle: 2.356
          min_angle: -2.356
          max_range: 1
          min_range: 0.001
          num_rays: 7
          frequency: 10
          frame_id: laser0
          pose:
            x: 0
            y: 0
            theta: 0
          noise:
            noise_specifications:
              noise_mean: 0
              noise_std: 0
